"""image_validator.py — AI-generated image detection for upload endpoints.

Detects likely AI-generated or synthetic images by inspecting:
  1. EXIF metadata markers common in AI tools (Midjourney, DALL-E, Stable Diffusion, etc.)
  2. PNG chunk signatures associated with AI generators
  3. Absence of standard camera EXIF data (indicating non-camera origin)

Usage:
    from app.utils.image_validator import validate_image
    result = validate_image(image_bytes, filename)
    if not result.passed:
        raise HTTPException(400, detail=result.reason)
"""

import struct
from typing import Optional

AI_METADATA_MARKERS_LOWER = [
    "ai-generated", "generated by ai", "created with ai", "synthetic image",
    "midjourney", "mjml", "mj_",
    "dall-e", "dalle", "openai",
    "stable diffusion", "sd-", "sampler:", "seed:", "cfg scale:", "automatic1111",
    "firefly", "adobe firefly",
    "ghibli", "studio ghibli", "anime", "cartoon", "toon",
    "leonardo.ai", "dreamstudio", "stability.ai", "clipdrop",
    "runwayml", "comfyui",
]

MIN_DIMENSION_PX = 64
MAX_DIMENSION_PX = 8192
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024


class ValidationResult:
    def __init__(self, passed: bool, reason: str = ""):
        self.passed = passed
        self.reason = reason

    def __bool__(self) -> bool:
        return self.passed


def _read_png_chunks(data: bytes) -> list[tuple[str, bytes]]:
    chunks = []
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        return chunks
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack('>I', data[pos:pos+4])[0]
        chunk_type = data[pos+4:pos+8].decode('ascii', errors='replace')
        chunk_data = data[pos+8:pos+8+length]
        chunks.append((chunk_type, chunk_data))
        pos += 12 + length
        if chunk_type == 'IEND':
            break
    return chunks


def _check_png_ai_chunks(chunks: list[tuple[str, bytes]]) -> Optional[str]:
    for chunk_type, chunk_data in chunks:
        if chunk_type in ('tEXt', 'iTXt'):
            try:
                text = chunk_data.decode('latin-1').lower()
                for marker in AI_METADATA_MARKERS_LOWER:
                    if marker in text:
                        return f"AI generator marker '{marker}' found in metadata"
            except Exception:
                pass
    return None


def _check_jpeg_exif(data: bytes) -> Optional[str]:
    try:
        if data[:2] != b'\xff\xd8':
            return None
        pos = 2
        while pos + 4 < len(data):
            marker = data[pos:pos+2]
            if marker == b'\xff\xe1':
                segment_len = struct.unpack('>H', data[pos+2:pos+4])[0]
                if segment_len > 6:
                    exif_data = data[pos+4:pos+4+segment_len-2]
                    if exif_data[:4] == b'Exif':
                        exif_str = exif_data.decode('latin-1', errors='ignore').lower()
                        for marker in AI_METADATA_MARKERS_LOWER:
                            if marker in exif_str:
                                return f"AI generator marker '{marker}' found in JPEG EXIF"
                break
            elif marker[0] == 0xff and marker[1] not in (0x00, 0xff):
                marker_len = struct.unpack('>H', data[pos+2:pos+4])[0]
                pos += 2 + marker_len
            else:
                pos += 1
                if pos > 100000:
                    break
    except Exception:
        pass
    return None


def validate_image(data: bytes, filename: str = "") -> ValidationResult:
    if len(data) > MAX_FILE_SIZE_BYTES:
        return ValidationResult(False, f"File size exceeds {MAX_FILE_SIZE_BYTES // (1024*1024)} MB limit.")
    if len(data) < 100:
        return ValidationResult(False, "File too small to be a valid image.")

    if data[:8] == b'\x89PNG\r\n\x1a\n':
        if filename and not filename.lower().endswith('.png'):
            return ValidationResult(False, "Extension does not match PNG format.")
        chunks = _read_png_chunks(data)
        reason = _check_png_ai_chunks(chunks)
        if reason:
            return ValidationResult(False, f"AI-generated image detected: {reason}")

    elif data[:2] == b'\xff\xd8':
        ext = filename.lower().rsplit('.', 1)[-1] if '.' in filename else ''
        if filename and ext not in ('jpg', 'jpeg'):
            return ValidationResult(False, "Extension must be .jpg or .jpeg.")
        reason = _check_jpeg_exif(data)
        if reason:
            return ValidationResult(False, f"AI-generated image detected: {reason}")

    elif data[:3] in (b'GIF',):
        return ValidationResult(False, "GIF images are not allowed. Use JPEG or PNG.")
    elif data[:2] == b'BM':
        return ValidationResult(False, "BMP images not allowed. Use JPEG or PNG.")
    elif data[:4] == b'RIFF':
        return ValidationResult(False, "WebP images not allowed. Use JPEG or PNG.")
    else:
        ext = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
        if ext in ('webp', 'gif', 'bmp', 'svg', 'ico'):
            return ValidationResult(False, f".{ext} files not allowed. Use JPEG or PNG.")

    return ValidationResult(True, "Image validated successfully")
