/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoterVoteRouteImport } from './routes/voter/vote'
import { Route as VoterStatisticsRouteImport } from './routes/voter/statistics'
import { Route as VoterSettingsRouteImport } from './routes/voter/settings'
import { Route as VoterResultsRouteImport } from './routes/voter/results'
import { Route as VoterOtpVerifyRouteImport } from './routes/voter/otp-verify'
import { Route as VoterNotificationsRouteImport } from './routes/voter/notifications'
import { Route as VoterMediaRouteImport } from './routes/voter/media'
import { Route as VoterDashboardRouteImport } from './routes/voter/dashboard'
import { Route as VoterConcernsRouteImport } from './routes/voter/concerns'
import { Route as VoterCandidatesRouteImport } from './routes/voter/candidates'
import { Route as VoterAiAssistantRouteImport } from './routes/voter/ai-assistant'
import { Route as CandidateStatusRouteImport } from './routes/candidate/status'
import { Route as CandidateSettingsRouteImport } from './routes/candidate/settings'
import { Route as CandidateRegisterRouteImport } from './routes/candidate/register'
import { Route as CandidatePartyDashboardRouteImport } from './routes/candidate/party-dashboard'
import { Route as CandidateOtpVerifyRouteImport } from './routes/candidate/otp-verify'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate/notifications'
import { Route as CandidateMediaRouteImport } from './routes/candidate/media'
import { Route as CandidateManifestoRouteImport } from './routes/candidate/manifesto'
import { Route as CandidateDashboardRouteImport } from './routes/candidate/dashboard'
import { Route as CandidateConcernsRouteImport } from './routes/candidate/concerns'
import { Route as CandidateApplyRouteImport } from './routes/candidate/apply'
import { Route as CandidateAiReportRouteImport } from './routes/candidate/ai-report'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminPendingPhotosRouteImport } from './routes/admin/pending-photos'
import { Route as AdminPartiesRouteImport } from './routes/admin/parties'
import { Route as AdminOtpVerifyRouteImport } from './routes/admin/otp-verify'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminMeetingsRouteImport } from './routes/admin/meetings'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminManifestosRouteImport } from './routes/admin/manifestos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminElectionRouteImport } from './routes/admin/election'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConcernsClustersRouteImport } from './routes/admin/concerns-clusters'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminCampusReportRouteImport } from './routes/admin/campus-report'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAiMonitoringRouteImport } from './routes/admin/ai-monitoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterVoteRoute = VoterVoteRouteImport.update({
  id: '/voter/vote',
  path: '/voter/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterStatisticsRoute = VoterStatisticsRouteImport.update({
  id: '/voter/statistics',
  path: '/voter/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterSettingsRoute = VoterSettingsRouteImport.update({
  id: '/voter/settings',
  path: '/voter/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterResultsRoute = VoterResultsRouteImport.update({
  id: '/voter/results',
  path: '/voter/results',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterOtpVerifyRoute = VoterOtpVerifyRouteImport.update({
  id: '/voter/otp-verify',
  path: '/voter/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterNotificationsRoute = VoterNotificationsRouteImport.update({
  id: '/voter/notifications',
  path: '/voter/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterMediaRoute = VoterMediaRouteImport.update({
  id: '/voter/media',
  path: '/voter/media',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterDashboardRoute = VoterDashboardRouteImport.update({
  id: '/voter/dashboard',
  path: '/voter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterConcernsRoute = VoterConcernsRouteImport.update({
  id: '/voter/concerns',
  path: '/voter/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterCandidatesRoute = VoterCandidatesRouteImport.update({
  id: '/voter/candidates',
  path: '/voter/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterAiAssistantRoute = VoterAiAssistantRouteImport.update({
  id: '/voter/ai-assistant',
  path: '/voter/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateStatusRoute = CandidateStatusRouteImport.update({
  id: '/candidate/status',
  path: '/candidate/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/candidate/settings',
  path: '/candidate/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRegisterRoute = CandidateRegisterRouteImport.update({
  id: '/candidate/register',
  path: '/candidate/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePartyDashboardRoute = CandidatePartyDashboardRouteImport.update({
  id: '/candidate/party-dashboard',
  path: '/candidate/party-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateOtpVerifyRoute = CandidateOtpVerifyRouteImport.update({
  id: '/candidate/otp-verify',
  path: '/candidate/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateMediaRoute = CandidateMediaRouteImport.update({
  id: '/candidate/media',
  path: '/candidate/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateManifestoRoute = CandidateManifestoRouteImport.update({
  id: '/candidate/manifesto',
  path: '/candidate/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateConcernsRoute = CandidateConcernsRouteImport.update({
  id: '/candidate/concerns',
  path: '/candidate/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplyRoute = CandidateApplyRouteImport.update({
  id: '/candidate/apply',
  path: '/candidate/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAiReportRoute = CandidateAiReportRouteImport.update({
  id: '/candidate/ai-report',
  path: '/candidate/ai-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingPhotosRoute = AdminPendingPhotosRouteImport.update({
  id: '/admin/pending-photos',
  path: '/admin/pending-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartiesRoute = AdminPartiesRouteImport.update({
  id: '/admin/parties',
  path: '/admin/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOtpVerifyRoute = AdminOtpVerifyRouteImport.update({
  id: '/admin/otp-verify',
  path: '/admin/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/admin/notices',
  path: '/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/admin/meetings',
  path: '/admin/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManifestosRoute = AdminManifestosRouteImport.update({
  id: '/admin/manifestos',
  path: '/admin/manifestos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElectionRoute = AdminElectionRouteImport.update({
  id: '/admin/election',
  path: '/admin/election',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConcernsClustersRoute = AdminConcernsClustersRouteImport.update({
  id: '/admin/concerns-clusters',
  path: '/admin/concerns-clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampusReportRoute = AdminCampusReportRouteImport.update({
  id: '/admin/campus-report',
  path: '/admin/campus-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiMonitoringRoute = AdminAiMonitoringRouteImport.update({
  id: '/admin/ai-monitoring',
  path: '/admin/ai-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-report': typeof AdminCampusReportRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/concerns-clusters': typeof AdminConcernsClustersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/election': typeof AdminElectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manifestos': typeof AdminManifestosRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otp-verify': typeof AdminOtpVerifyRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/pending-photos': typeof AdminPendingPhotosRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/ai-report': typeof CandidateAiReportRoute
  '/candidate/apply': typeof CandidateApplyRoute
  '/candidate/concerns': typeof CandidateConcernsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/manifesto': typeof CandidateManifestoRoute
  '/candidate/media': typeof CandidateMediaRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/otp-verify': typeof CandidateOtpVerifyRoute
  '/candidate/party-dashboard': typeof CandidatePartyDashboardRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/voter/ai-assistant': typeof VoterAiAssistantRoute
  '/voter/candidates': typeof VoterCandidatesRoute
  '/voter/concerns': typeof VoterConcernsRoute
  '/voter/dashboard': typeof VoterDashboardRoute
  '/voter/media': typeof VoterMediaRoute
  '/voter/notifications': typeof VoterNotificationsRoute
  '/voter/otp-verify': typeof VoterOtpVerifyRoute
  '/voter/results': typeof VoterResultsRoute
  '/voter/settings': typeof VoterSettingsRoute
  '/voter/statistics': typeof VoterStatisticsRoute
  '/voter/vote': typeof VoterVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-report': typeof AdminCampusReportRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/concerns-clusters': typeof AdminConcernsClustersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/election': typeof AdminElectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manifestos': typeof AdminManifestosRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otp-verify': typeof AdminOtpVerifyRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/pending-photos': typeof AdminPendingPhotosRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/ai-report': typeof CandidateAiReportRoute
  '/candidate/apply': typeof CandidateApplyRoute
  '/candidate/concerns': typeof CandidateConcernsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/manifesto': typeof CandidateManifestoRoute
  '/candidate/media': typeof CandidateMediaRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/otp-verify': typeof CandidateOtpVerifyRoute
  '/candidate/party-dashboard': typeof CandidatePartyDashboardRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/voter/ai-assistant': typeof VoterAiAssistantRoute
  '/voter/candidates': typeof VoterCandidatesRoute
  '/voter/concerns': typeof VoterConcernsRoute
  '/voter/dashboard': typeof VoterDashboardRoute
  '/voter/media': typeof VoterMediaRoute
  '/voter/notifications': typeof VoterNotificationsRoute
  '/voter/otp-verify': typeof VoterOtpVerifyRoute
  '/voter/results': typeof VoterResultsRoute
  '/voter/settings': typeof VoterSettingsRoute
  '/voter/statistics': typeof VoterStatisticsRoute
  '/voter/vote': typeof VoterVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/ai-monitoring': typeof AdminAiMonitoringRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campus-report': typeof AdminCampusReportRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/concerns-clusters': typeof AdminConcernsClustersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/election': typeof AdminElectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manifestos': typeof AdminManifestosRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otp-verify': typeof AdminOtpVerifyRoute
  '/admin/parties': typeof AdminPartiesRoute
  '/admin/pending-photos': typeof AdminPendingPhotosRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/ai-report': typeof CandidateAiReportRoute
  '/candidate/apply': typeof CandidateApplyRoute
  '/candidate/concerns': typeof CandidateConcernsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/manifesto': typeof CandidateManifestoRoute
  '/candidate/media': typeof CandidateMediaRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/otp-verify': typeof CandidateOtpVerifyRoute
  '/candidate/party-dashboard': typeof CandidatePartyDashboardRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/voter/ai-assistant': typeof VoterAiAssistantRoute
  '/voter/candidates': typeof VoterCandidatesRoute
  '/voter/concerns': typeof VoterConcernsRoute
  '/voter/dashboard': typeof VoterDashboardRoute
  '/voter/media': typeof VoterMediaRoute
  '/voter/notifications': typeof VoterNotificationsRoute
  '/voter/otp-verify': typeof VoterOtpVerifyRoute
  '/voter/results': typeof VoterResultsRoute
  '/voter/settings': typeof VoterSettingsRoute
  '/voter/statistics': typeof VoterStatisticsRoute
  '/voter/vote': typeof VoterVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/ai-monitoring'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/campus-report'
    | '/admin/candidates'
    | '/admin/concerns-clusters'
    | '/admin/dashboard'
    | '/admin/election'
    | '/admin/login'
    | '/admin/manifestos'
    | '/admin/media'
    | '/admin/meetings'
    | '/admin/notices'
    | '/admin/otp-verify'
    | '/admin/parties'
    | '/admin/pending-photos'
    | '/admin/results'
    | '/admin/settings'
    | '/candidate/ai-report'
    | '/candidate/apply'
    | '/candidate/concerns'
    | '/candidate/dashboard'
    | '/candidate/manifesto'
    | '/candidate/media'
    | '/candidate/notifications'
    | '/candidate/otp-verify'
    | '/candidate/party-dashboard'
    | '/candidate/register'
    | '/candidate/settings'
    | '/candidate/status'
    | '/voter/ai-assistant'
    | '/voter/candidates'
    | '/voter/concerns'
    | '/voter/dashboard'
    | '/voter/media'
    | '/voter/notifications'
    | '/voter/otp-verify'
    | '/voter/results'
    | '/voter/settings'
    | '/voter/statistics'
    | '/voter/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/ai-monitoring'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/campus-report'
    | '/admin/candidates'
    | '/admin/concerns-clusters'
    | '/admin/dashboard'
    | '/admin/election'
    | '/admin/login'
    | '/admin/manifestos'
    | '/admin/media'
    | '/admin/meetings'
    | '/admin/notices'
    | '/admin/otp-verify'
    | '/admin/parties'
    | '/admin/pending-photos'
    | '/admin/results'
    | '/admin/settings'
    | '/candidate/ai-report'
    | '/candidate/apply'
    | '/candidate/concerns'
    | '/candidate/dashboard'
    | '/candidate/manifesto'
    | '/candidate/media'
    | '/candidate/notifications'
    | '/candidate/otp-verify'
    | '/candidate/party-dashboard'
    | '/candidate/register'
    | '/candidate/settings'
    | '/candidate/status'
    | '/voter/ai-assistant'
    | '/voter/candidates'
    | '/voter/concerns'
    | '/voter/dashboard'
    | '/voter/media'
    | '/voter/notifications'
    | '/voter/otp-verify'
    | '/voter/results'
    | '/voter/settings'
    | '/voter/statistics'
    | '/voter/vote'
  id:
    | '__root__'
    | '/'
    | '/admin/ai-monitoring'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/campus-report'
    | '/admin/candidates'
    | '/admin/concerns-clusters'
    | '/admin/dashboard'
    | '/admin/election'
    | '/admin/login'
    | '/admin/manifestos'
    | '/admin/media'
    | '/admin/meetings'
    | '/admin/notices'
    | '/admin/otp-verify'
    | '/admin/parties'
    | '/admin/pending-photos'
    | '/admin/results'
    | '/admin/settings'
    | '/candidate/ai-report'
    | '/candidate/apply'
    | '/candidate/concerns'
    | '/candidate/dashboard'
    | '/candidate/manifesto'
    | '/candidate/media'
    | '/candidate/notifications'
    | '/candidate/otp-verify'
    | '/candidate/party-dashboard'
    | '/candidate/register'
    | '/candidate/settings'
    | '/candidate/status'
    | '/voter/ai-assistant'
    | '/voter/candidates'
    | '/voter/concerns'
    | '/voter/dashboard'
    | '/voter/media'
    | '/voter/notifications'
    | '/voter/otp-verify'
    | '/voter/results'
    | '/voter/settings'
    | '/voter/statistics'
    | '/voter/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAiMonitoringRoute: typeof AdminAiMonitoringRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCampusReportRoute: typeof AdminCampusReportRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminConcernsClustersRoute: typeof AdminConcernsClustersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminElectionRoute: typeof AdminElectionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManifestosRoute: typeof AdminManifestosRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminOtpVerifyRoute: typeof AdminOtpVerifyRoute
  AdminPartiesRoute: typeof AdminPartiesRoute
  AdminPendingPhotosRoute: typeof AdminPendingPhotosRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CandidateAiReportRoute: typeof CandidateAiReportRoute
  CandidateApplyRoute: typeof CandidateApplyRoute
  CandidateConcernsRoute: typeof CandidateConcernsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateManifestoRoute: typeof CandidateManifestoRoute
  CandidateMediaRoute: typeof CandidateMediaRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateOtpVerifyRoute: typeof CandidateOtpVerifyRoute
  CandidatePartyDashboardRoute: typeof CandidatePartyDashboardRoute
  CandidateRegisterRoute: typeof CandidateRegisterRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  CandidateStatusRoute: typeof CandidateStatusRoute
  VoterAiAssistantRoute: typeof VoterAiAssistantRoute
  VoterCandidatesRoute: typeof VoterCandidatesRoute
  VoterConcernsRoute: typeof VoterConcernsRoute
  VoterDashboardRoute: typeof VoterDashboardRoute
  VoterMediaRoute: typeof VoterMediaRoute
  VoterNotificationsRoute: typeof VoterNotificationsRoute
  VoterOtpVerifyRoute: typeof VoterOtpVerifyRoute
  VoterResultsRoute: typeof VoterResultsRoute
  VoterSettingsRoute: typeof VoterSettingsRoute
  VoterStatisticsRoute: typeof VoterStatisticsRoute
  VoterVoteRoute: typeof VoterVoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/vote': {
      id: '/voter/vote'
      path: '/voter/vote'
      fullPath: '/voter/vote'
      preLoaderRoute: typeof VoterVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/statistics': {
      id: '/voter/statistics'
      path: '/voter/statistics'
      fullPath: '/voter/statistics'
      preLoaderRoute: typeof VoterStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/settings': {
      id: '/voter/settings'
      path: '/voter/settings'
      fullPath: '/voter/settings'
      preLoaderRoute: typeof VoterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/results': {
      id: '/voter/results'
      path: '/voter/results'
      fullPath: '/voter/results'
      preLoaderRoute: typeof VoterResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/otp-verify': {
      id: '/voter/otp-verify'
      path: '/voter/otp-verify'
      fullPath: '/voter/otp-verify'
      preLoaderRoute: typeof VoterOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/notifications': {
      id: '/voter/notifications'
      path: '/voter/notifications'
      fullPath: '/voter/notifications'
      preLoaderRoute: typeof VoterNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/media': {
      id: '/voter/media'
      path: '/voter/media'
      fullPath: '/voter/media'
      preLoaderRoute: typeof VoterMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/dashboard': {
      id: '/voter/dashboard'
      path: '/voter/dashboard'
      fullPath: '/voter/dashboard'
      preLoaderRoute: typeof VoterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/concerns': {
      id: '/voter/concerns'
      path: '/voter/concerns'
      fullPath: '/voter/concerns'
      preLoaderRoute: typeof VoterConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/candidates': {
      id: '/voter/candidates'
      path: '/voter/candidates'
      fullPath: '/voter/candidates'
      preLoaderRoute: typeof VoterCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter/ai-assistant': {
      id: '/voter/ai-assistant'
      path: '/voter/ai-assistant'
      fullPath: '/voter/ai-assistant'
      preLoaderRoute: typeof VoterAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/status': {
      id: '/candidate/status'
      path: '/candidate/status'
      fullPath: '/candidate/status'
      preLoaderRoute: typeof CandidateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/candidate/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/register': {
      id: '/candidate/register'
      path: '/candidate/register'
      fullPath: '/candidate/register'
      preLoaderRoute: typeof CandidateRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/party-dashboard': {
      id: '/candidate/party-dashboard'
      path: '/candidate/party-dashboard'
      fullPath: '/candidate/party-dashboard'
      preLoaderRoute: typeof CandidatePartyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/otp-verify': {
      id: '/candidate/otp-verify'
      path: '/candidate/otp-verify'
      fullPath: '/candidate/otp-verify'
      preLoaderRoute: typeof CandidateOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/media': {
      id: '/candidate/media'
      path: '/candidate/media'
      fullPath: '/candidate/media'
      preLoaderRoute: typeof CandidateMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/manifesto': {
      id: '/candidate/manifesto'
      path: '/candidate/manifesto'
      fullPath: '/candidate/manifesto'
      preLoaderRoute: typeof CandidateManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/concerns': {
      id: '/candidate/concerns'
      path: '/candidate/concerns'
      fullPath: '/candidate/concerns'
      preLoaderRoute: typeof CandidateConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/apply': {
      id: '/candidate/apply'
      path: '/candidate/apply'
      fullPath: '/candidate/apply'
      preLoaderRoute: typeof CandidateApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/ai-report': {
      id: '/candidate/ai-report'
      path: '/candidate/ai-report'
      fullPath: '/candidate/ai-report'
      preLoaderRoute: typeof CandidateAiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending-photos': {
      id: '/admin/pending-photos'
      path: '/admin/pending-photos'
      fullPath: '/admin/pending-photos'
      preLoaderRoute: typeof AdminPendingPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parties': {
      id: '/admin/parties'
      path: '/admin/parties'
      fullPath: '/admin/parties'
      preLoaderRoute: typeof AdminPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/otp-verify': {
      id: '/admin/otp-verify'
      path: '/admin/otp-verify'
      fullPath: '/admin/otp-verify'
      preLoaderRoute: typeof AdminOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/admin/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manifestos': {
      id: '/admin/manifestos'
      path: '/admin/manifestos'
      fullPath: '/admin/manifestos'
      preLoaderRoute: typeof AdminManifestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/election': {
      id: '/admin/election'
      path: '/admin/election'
      fullPath: '/admin/election'
      preLoaderRoute: typeof AdminElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/concerns-clusters': {
      id: '/admin/concerns-clusters'
      path: '/admin/concerns-clusters'
      fullPath: '/admin/concerns-clusters'
      preLoaderRoute: typeof AdminConcernsClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campus-report': {
      id: '/admin/campus-report'
      path: '/admin/campus-report'
      fullPath: '/admin/campus-report'
      preLoaderRoute: typeof AdminCampusReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-monitoring': {
      id: '/admin/ai-monitoring'
      path: '/admin/ai-monitoring'
      fullPath: '/admin/ai-monitoring'
      preLoaderRoute: typeof AdminAiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAiMonitoringRoute: AdminAiMonitoringRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCampusReportRoute: AdminCampusReportRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminConcernsClustersRoute: AdminConcernsClustersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminElectionRoute: AdminElectionRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManifestosRoute: AdminManifestosRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminOtpVerifyRoute: AdminOtpVerifyRoute,
  AdminPartiesRoute: AdminPartiesRoute,
  AdminPendingPhotosRoute: AdminPendingPhotosRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CandidateAiReportRoute: CandidateAiReportRoute,
  CandidateApplyRoute: CandidateApplyRoute,
  CandidateConcernsRoute: CandidateConcernsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateManifestoRoute: CandidateManifestoRoute,
  CandidateMediaRoute: CandidateMediaRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateOtpVerifyRoute: CandidateOtpVerifyRoute,
  CandidatePartyDashboardRoute: CandidatePartyDashboardRoute,
  CandidateRegisterRoute: CandidateRegisterRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  CandidateStatusRoute: CandidateStatusRoute,
  VoterAiAssistantRoute: VoterAiAssistantRoute,
  VoterCandidatesRoute: VoterCandidatesRoute,
  VoterConcernsRoute: VoterConcernsRoute,
  VoterDashboardRoute: VoterDashboardRoute,
  VoterMediaRoute: VoterMediaRoute,
  VoterNotificationsRoute: VoterNotificationsRoute,
  VoterOtpVerifyRoute: VoterOtpVerifyRoute,
  VoterResultsRoute: VoterResultsRoute,
  VoterSettingsRoute: VoterSettingsRoute,
  VoterStatisticsRoute: VoterStatisticsRoute,
  VoterVoteRoute: VoterVoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
